tplProjectName: mobilebuilder_tpl_7_7_0
â†“LoginComponent [mobile.components.UISharedComponent-1572604124714]: ğŸ— mobileSharedComponents/LoginComponent.yaml
â†“Page [mobile.components.PageComponent-1572604056200]: ğŸ— mobilePages/Page.yaml
â†“ModalPopup [mobile.components.PageComponent-1572623654326]: ğŸ— mobilePages/ModalPopup.yaml