tplProjectName: mobilebuilder_tpl_7_6_0
â†“Menu [mobile.components.UIDynamicMenu-1562069116561]: ğŸ— mobileMenus/Menu.yaml
â†“ChatBot [mobile.components.UISharedComponent-1562052281347]: ğŸ— mobileSharedComponents/ChatBot.yaml
â†“Page [mobile.components.PageComponent-1562069093658]: ğŸ— mobilePages/Page.yaml