componentScriptContent: 
  - xmlizable: 
    - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      â†’: |
        /*Begin_c8o_AppImport*/
        /*End_c8o_AppImport*/
        /*Begin_c8o_AppDeclaration*/
        	/*End_c8o_AppDeclaration*/
        /*Begin_c8o_AppConstructor*/
        		/*End_c8o_AppConstructor*/
        /*Begin_c8o_AppInitialization*/
                        if (window["cordova"]) {
                            statusBar.backgroundColorByHexString("#253cbc");
                            statusBar.styleLightContent();
                        }
        			/*End_c8o_AppInitialization*/
        /*Begin_c8o_AppFunction*/
        	/*End_c8o_AppFunction*/
        
tplProjectName: mobilebuilder_tpl_7_5_2
â†“ShowFlightRoute [mobile.components.RouteComponent-1509555963318]: 
  â†“FullSyncEvent [mobile.components.RouteFullsyncEvent-1509555977898]: 
    marker: SHOWFLIGHT
    source: FlightShare.flightshare_fullsync
    verb: view
  â†“DataAction [mobile.components.RouteDataActionComponent-1509556023242]: 
    action: push
    page: FlightShare.MobileApplication.Application.MyFlightDetails
â†“ShowPublishedFlightDetailsRoute [mobile.components.RouteComponent-1509603236155]: 
  â†“FullSyncEvent [mobile.components.RouteFullsyncEvent-1509603249642]: 
    marker: SHOWPUBLISHEDFLIGHTSDETAILS
    source: FlightShare.flightshare_fullsync
    verb: view
  â†“DataAction [mobile.components.RouteDataActionComponent-1509603272855]: 
    action: push
    page: FlightShare.MobileApplication.Application.PublishedFlightDetails
â†“ModifyFlightRoute [mobile.components.RouteComponent-1511089274186]: 
  â†“FullSyncEvent [mobile.components.RouteFullsyncEvent-1511089299073]: 
    marker: MODIFYFLIGHT
    source: FlightShare.flightshare_fullsync
    verb: view
  â†“DataAction [mobile.components.RouteDataActionComponent-1511089390479]: 
    action: push
    condition: true
    page: FlightShare.MobileApplication.Application.AddOrModifyFlight
â†“ShowUserDetails [mobile.components.RouteComponent-1511712824537]: 
  â†“FullSyncEvent [mobile.components.RouteFullsyncEvent-1511712846600]: 
    marker: SHOWUSERDETAILS
    source: FlightShare.flightshare_fullsync
    verb: view
  â†“DataAction [mobile.components.RouteDataActionComponent-1511712898700]: 
    action: push
    condition: true
    page: FlightShare.MobileApplication.Application.UserDetails
â†“Menu [mobile.components.UIDynamicMenu-1500890597895]: ğŸ— mobileMenus/Menu.yaml
â†“Synchronizing [mobile.components.PageComponent-1510002425268]: ğŸ— mobilePages/Synchronizing.yaml
â†“Page [mobile.components.PageComponent-1500538678074]: ğŸ— mobilePages/Page.yaml
â†“MyFlights [mobile.components.PageComponent-1508938153011]: ğŸ— mobilePages/MyFlights.yaml
â†“SharedFlights [mobile.components.PageComponent-1508945918740]: ğŸ— mobilePages/SharedFlights.yaml
â†“PublishedFlightDetails [mobile.components.PageComponent-1509602577319]: ğŸ— mobilePages/PublishedFlightDetails.yaml
â†“MyFlightDetails [mobile.components.PageComponent-1508947432393]: ğŸ— mobilePages/MyFlightDetails.yaml
â†“AddOrModifyFlight [mobile.components.PageComponent-1508950679287]: ğŸ— mobilePages/AddOrModifyFlight.yaml
â†“ListAirports [mobile.components.PageComponent-1508989607361]: ğŸ— mobilePages/ListAirports.yaml
â†“SelectPlane [mobile.components.PageComponent-1509076849897]: ğŸ— mobilePages/SelectPlane.yaml
â†“Configuration [mobile.components.PageComponent-1509566884227]: ğŸ— mobilePages/Configuration.yaml
â†“UserDetails [mobile.components.PageComponent-1511712075424]: ğŸ— mobilePages/UserDetails.yaml
â†“UserList [mobile.components.PageComponent-1511716843845]: ğŸ— mobilePages/UserList.yaml
â†“Theme [mobile.components.UITheme-1491635018260]: 
  comment: Global color themes can be customized here
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '// Ionic Variables and Theming. For more info, please see:
          // http://ionicframework.com/docs/v2/theming/ 
          $font-path: "../assets/fonts";
          
          @import "ionic.globals";
          
          
          // Shared Variables
          // --------------------------------------------------
          // To customize the look and feel of this app, you can override
          // the Sass variables found in Ionic''s source scss files.
          // To view all the possible Ionic variables, see:
          // http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/
          
          
          
          
          // Named Color Variables
          // --------------------------------------------------
          // Named colors makes it easy to reuse colors on various components.
          // It''s highly recommended to change the default colors
          // to match your app''s branding. Ionic uses a Sass map of
          // colors so you can add, rename and remove colors as needed.
          // The "primary" color is the only required color in the map.
          
          $colors: (
                  primary:    #387ef5,
                  secondary:  #32db64,
                  danger:     #f53d3d,
                  light:      #253cbc,
                  dark:       #222
          );
          
          
          // App iOS Variables
          // --------------------------------------------------
          // iOS only Sass variables can go here
          
          
          
          
          // App Material Design Variables
          // --------------------------------------------------
          // Material Design only Sass variables can go here
          
          
          
          
          // App Windows Variables
          // --------------------------------------------------
          // Windows only Sass variables can go here
          
          
          
          
          // App Theme
          // --------------------------------------------------
          // Ionic apps can have different themes applied, which can
          // then be future customized. This import comes last
          // so that the above variables are used and Ionic''s
          // default are overridden.
          
          @import "ionic.theme.default";
          
          
          // Ionicons
          // --------------------------------------------------
          // The premium icon font for Ionic. For more info, please see:
          // http://ionicframework.com/docs/v2/ionicons/
          
          @import "ionic.ionicons";
          
          
          // Fonts
          // --------------------------------------------------
          
          @import "roboto";
          @import "noto-sans";'
â†“Style [mobile.components.UIStyle-1491635462437]: 
  comment: You can add some global application styles here
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '.content {
          	/* add some styling CSS rules here for the body of your app
          	   for example,
          	 		background-color: your color; 
          	 		background-image: url(some background image);
          	*/
          }
          
          .toolbar-background {
          	/* add some styling CSS rules here for the Headers and Footers
          	   for example,
          	background-color: #253cbc !important
          	*/
          	background-color: #253cbc
          	
          }
          
          // Make Menu icons separated from text
          .menu-inner ion-icon {
          	padding-right: 20px
          }'